### ISSUE TITLE
daily scrum (16/03/2016) #3

### ISSUE THREAD

**Issue by poysrnp** [Mergano/restaurant#3]
What did you do yesterday?
talk about database

What will you do today?
talk about database
talk about design pattern
talk about GUI

Is anything in your way?
Nothing

![12325516_10201601056184602_1088517079_o](https://cloud.githubusercontent.com/assets/16892565/13810059/5d597aec-eba0-11e5-964e-12c51b8e58f6.jpg)

**Comment by aeyvaristha** [comment]
What did you do yesterday?
Discuss about the database system.

What will you do today?
Distribute about responsbility for each member.
Design each UI pages.

Is anything in your way?
Nothing
